app/main_page_module/models.py
# Import the database object (db) from the main application module
from app import db

# Import password / encryption helper tools
from werkzeug import check_password_hash, generate_password_hash

# Define a base model for other database tables to inherit
class Base(db.Model):

    __abstract__  = True

    id = db.Column(db.Integer, primary_key=True)
    date_created  = db.Column(db.DateTime,  default=db.func.current_timestamp())
    date_modified = db.Column(db.DateTime,  default=db.func.current_timestamp(),
                              onupdate=db.func.current_timestamp())

# Define a User model
class User(Base):

    __tablename__ = 'users_table'

    # User Name
    name    = db.Column(db.String(128),  nullable=False)
    
    # UserName
    username    = db.Column(db.String(128),  nullable=False,
                            unique=True)    

    # Identification Data: email & password
    email    = db.Column(db.String(128),  nullable=False,
                         unique=True)
    password = db.Column(db.String(192),  nullable=False)

    # Authorisation Data: role & status
    role     = db.Column(db.SmallInteger, nullable=False)
    status   = db.Column(db.SmallInteger, nullable=False)
    

    # New instance instantiation procedure
    def __init__(self, username, email, password):

        self.name     = username
        self.username = username
        self.email    = email
        self.password = password
        self.role = 0
        self.status = 1

    def __repr__(self):
        return '<User %r>' % (self.name)
    
    def set_password(self, password):
            self.password = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password, password) 

# Define a User model
class Entry(Base):

    __tablename__ = 'entrytable'

    # User Name
    name    = db.Column(db.String(128),  nullable=False,
                            unique=True)
    
    # filename
    filename    = db.Column(db.String(128),  nullable=False,
                            unique=True)    
    

    # New instance instantiation procedure
    def __init__(self, name, filename):

        self.name     = name
        self.filename = filename

    def __repr__(self):
        return '<User %r>' % (self.name)

app/main_page_module/forms.py
# Import Form and RecaptchaField (optional)
from flask_wtf import FlaskForm # , RecaptchaField

# Import Form elements such as TextField and BooleanField (optional)
from wtforms import BooleanField, StringField, TextAreaField, PasswordField, HiddenField, SubmitField, validators # BooleanField

# Import Form validators
from wtforms.validators import Email, EqualTo, ValidationError

from app.main_page_module.models import User

#email verification
import re
import os.path


# Define the login form (WTForms)

class EditEntryForm(FlaskForm):

    entry_text = TextAreaField('Entry Text', [validators.InputRequired(message='You need to fill something.')])
    
    submit = SubmitField('Submit changes')
    
class EntryForm(FlaskForm):
    name = StringField('Name of new entry', [validators.InputRequired(message='You need to specify a name'),
                                             validators.Length(max=128)])
    entry_text = TextAreaField('Entry Text', [validators.InputRequired(message='You need to fill something.')])
    
    submit = SubmitField('Add Entry')
    
    def validate_name(self, name):
        
        #check if there is another entry with the same name
        name = str(name.data).strip().replace(' ', '_') 
        name = re.sub(r'(?u)[^-\w.]', '', name)
        
        storage_location = "app//main_page_module//data//"
        files = []
        # r=root, d=directories, f = files
        for _, _, f in os.walk(storage_location):
            for file in f:
                if '.txt' in file:
                    files.append(file)  
        
        if name+".txt" in files:
            raise ValidationError('Entry already exists. Please use a different name for the entry')     
      

class LoginForm(FlaskForm):
    username_or_email = StringField('Username or Email', [validators.InputRequired(message='Forgot your email address?')])
    password = PasswordField('Password', [validators.InputRequired(message='Must provide a password.')])
    remember = BooleanField()
    
    submit = SubmitField('Login')

class EditUserForm(FlaskForm):

    id = HiddenField('id', [validators.InputRequired(message='Dont fiddle around with the code!')])
    name   = StringField('Name', [validators.InputRequired(message='We need a name for the user.')])
    email    = StringField('Email', [validators.InputRequired(message='We need an email for your account.')])
    password  = PasswordField('Password')    
    password_2 = PasswordField('Repeat password', [EqualTo('password', message='Passwords must match')])
      
    submit = SubmitField('Submit changes')
    

class RegisterForm(FlaskForm):
    username   = StringField('Username', [validators.InputRequired(message='We need a username for your account.')])
    email    = StringField('Email', [validators.InputRequired(message='We need an email for your account.')])
    password  = PasswordField('Password')    
    password_2 = PasswordField('Repeat password', [validators.InputRequired(), EqualTo('password', message='Passwords must match')])
    
    submit = SubmitField('Register')
    
    #When you add any methods that match the pattern validate_<field_name>, WTForms takes those as custom validators and invokes them in addition to the stock validators
    def validate_username(self, username):
            user = User.query.filter_by(username=username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')
    
    def validate_email(self, email):
        
        regex = '^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$'
        
        #check if it is a real email
        if(re.search(regex,email.data)):  
            #if it is, check if there is another user with the same email
            user = User.query.filter_by(email=email.data).first()
        
            if user is not None:
                raise ValidationError('Please use a different email address.')     
        
        else:  
            raise ValidationError('Please use a valid email address.')          
        
        

app/main_page_module/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for, jsonify, send_file
# Import the database object from the main app module
from app import db

# Import module forms
from app.main_page_module.forms import LoginForm, RegisterForm, EntryForm, EditEntryForm, EditUserForm

# Import module models (i.e. User)
from app.main_page_module.models import User
#import os
import re
import os
import zipfile
import io
import pathlib
from functools import wraps
import datetime


from app.main_page_module.argus import WSearch

# Define the blueprint: 'auth', set its url prefix: app.url/auth
main_page_module = Blueprint('main_page_module', __name__, url_prefix='/')

#login decorator
def login_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if 'user_id' in session:
            return f(*args, **kwargs)
        
        else:
            flash("Please login to access the site.", "error")
            
            return redirect(url_for("main_page_module.login"))
    
    return wrapper


#login check
def check_login():
    if "user_id" not in session:
        return True
    
# Set the route and accepted methods
@main_page_module.route('/', methods=['GET', 'POST'])
@login_required
def index():
    #if check_login(): return redirect(url_for("main_page_module.login"))  

    return render_template("main_page_module/index.html")

@main_page_module.route('/search/', methods=['POST'])
@login_required
def searc_results():
    key = request.form["key"]
    
    banana = WSearch()
    if key == "":
        asterix = ""
    else:
        asterix = "*"
    res = banana.index_search(key + asterix)    

    results = {str(r[0][29:-4]).strip().replace('_', ' ').capitalize(): [str(r[0][29:-4]).strip(), r[1]] for r in res}
    
    #print(results)
    return jsonify(results)

@main_page_module.route('/delete/', methods=['POST'])
@login_required
def delete_entry():
    entry_id = request.form["id"]
    name = str(entry_id).strip().replace(' ', '_')
    
    banana = f"app//main_page_module//data//{name}.txt"
    if os.path.exists(banana):
        os.remove(banana)
        
        #update argus index
        new_index = WSearch()
        new_index.index_create()        
        
        flash('Entry successfully deleted.', 'success')
        
        return redirect(url_for("main_page_module.index"))      
      
    else:
        flash('No entries with this name found to delete.', 'error')
        
        return redirect(url_for("main_page_module.index"))        


@main_page_module.route('/new_entry', methods=['GET', 'POST'])
@login_required
def new_entry():
    # If sign in form is submitted
    form = EntryForm(request.form)
    
    # Verify the sign in form
    if form.validate_on_submit():
        name = str(form.name.data).strip().replace(' ', '_') 
        name = re.sub(r'(?u)[^-\w.]', '', name)        
        new_filename = "app//main_page_module//data//" + name + ".txt"
        #print(os.getcwd())
        with open(f'{new_filename}', 'w') as file:
                file.write(form.entry_text.data)
        
        #create argus index
        new_index = WSearch()
        new_index.index_create()
        
        flash('Entry successfully created!', 'success')
        flash('Argus index successfully updated', 'success')
        
        return redirect(f"view_entry/{name}")
        #return redirect(url_for("main_page_module.view_entry"), entry_name=new_filename)

    return render_template("main_page_module/new_entry.html", form=form)

@main_page_module.route('/all_entry/')
@login_required
def all_entry():
    storage_location = "app//main_page_module//data//"
    
    files = []
    # r=root, d=directories, f = files
    for _, _, f in os.walk(storage_location):
        for file in f:
            if '.txt' in file:
                name_for_link = str(file).strip().replace(' ', '_')[:-4]
                files.append([os.path.join(storage_location, file), file[:-4].replace('_', ' ').capitalize(), name_for_link])

   
    return render_template("main_page_module/all_entry.html", files=files)

@main_page_module.route('/view_entry/<entry_name>', methods=['GET', 'POST'])
@login_required
def view_entry(entry_name):
    title = str(entry_name).strip().replace('_', ' ').capitalize()
    text = ""
    
    try:
        banana = f"app//main_page_module//data//{entry_name}.txt"
        #http://127.0.0.1:5000/view_entry/apre_ticket
        with open(banana, 'r') as file:
            
            text = file.read()

    except:
        flash('No entries with this name found', 'error')
        
        return redirect(url_for("main_page_module.index"))

    print(entry_name)
    return render_template("main_page_module/view_entry.html", entry_name=title, entry_text=text, link_entry_name=entry_name)

@main_page_module.route('/edit_entry/<entry_name>', methods=['GET', 'POST'])
@login_required
def edit_entry(entry_name):
    title = str(entry_name).strip().replace('_', ' ').capitalize()
    text = ""
    banana = f"app//main_page_module//data//{entry_name}.txt"
    form = EditEntryForm(request.form)
    #verify if the file exists
    if not os.path.exists(banana):
        flash('No entries with this name found ' + f"view_entry/{entry_name}", 'error')
        
        return redirect(url_for("main_page_module.index"))
    
    # Verify the sign in form
    if form.validate_on_submit():
        with open(banana, 'w') as file:
            #print(repr(form.entry_text.data))
            escaped_text = form.entry_text.data.replace("\r", "")
            file.write(escaped_text)
        
        #create argus index
        new_index = WSearch()
        new_index.index_create()
        
        flash('Entry successfully Eddited!', 'success')
        flash('Argus index successfully updated', 'success')
        
        #return redirect(f"/view_entry/{entry_name}")
        return redirect(url_for("main_page_module.view_entry", entry_name=entry_name))
        #return redirect(url_for("main_page_module.view_entry"), entry_name=new_filename)
    else:
        with open(banana, 'r') as file:
            text = file.read()
            #print(repr(text))

    return render_template("main_page_module/edit_entry.html", entry_name=title, entry_text=text, link_entry_name=entry_name, form=form)


@main_page_module.route('/get_zipped_entries/')
@login_required
def get_zipped_entries():
    now = datetime.datetime.now()
    
    base_path = pathlib.Path('app//main_page_module//data//')
    data = io.BytesIO()
    with zipfile.ZipFile(data, mode='w') as z:
        for f_name in base_path.iterdir():
            print
            z.write(f_name, os.path.basename(f_name))
    data.seek(0)
    
    return send_file(
        data,
        mimetype='application/zip',
        as_attachment=True,
        attachment_filename=f'all_entries_{now.strftime("%Y-%m-%d_%H-%M")}.zip',
        cache_timeout=0
    )


@main_page_module.route('/admin/all_users/')
@login_required
def all_users():
    users = User.query.all()
   
    return render_template("main_page_module/admin/all_users.html", users=users)


@main_page_module.route('/admin/view_user/<user_id>')
@login_required
def view_user(user_id):
    user = User.query.filter_by(id=user_id).first()
   
    if not user:
        flash('User does not exist.', 'error')
        
        return redirect(url_for("main_page_module.all_users"))     
    
    form = EditUserForm()
    form.process(obj=user)
    
   
    return render_template("main_page_module/admin/view_user.html", form=form, user=user)

@main_page_module.route('/admin/modify_user/', methods=['POST'])
@login_required
def modify_user():
    form = EditUserForm(request.form)
    
    if form.validate_on_submit():
        user = User.query.filter_by(id=form.id.data).first()
        
        if not user:
            flash('User does not exist.', 'error')
        
            return redirect(url_for("main_page_module.all_users")) 
        
        else:
            user.name =  form.name.data
            user.email =  form.email.data
            if form.password.data != "":
                user.set_password(form.password.data)
    
            db.session.commit()   
        
        flash('User successfully Eddited!', 'success')
        
        return redirect(url_for("main_page_module.view_user", user_id=form.id.data, form=form))
    
    flash('Invalid data.', 'error')

    return redirect(url_for("main_page_module.all_users"))     
    

@main_page_module.route('/admin/delete/', methods=['POST'])
@login_required
def delete_user():
    user_id = request.form["id"]
    
    user = User.query.filter_by(id=user_id).first()
   
    if not user:
        flash('User does not exist.', 'error')
        
        return redirect(url_for("main_page_module.all_users")) 
    
    else:
        db.session.delete(user)
        db.session.commit()        
        
        flash(f'User {user.name} - {user.username} successfully deleted.', 'success')
        
        return redirect(url_for("main_page_module.all_users")) 
    

# Set the route and accepted methods
@main_page_module.route('/login/', methods=['GET', 'POST'])
def login():

    # If sign in form is submitted
    form = LoginForm(request.form)
    

    # Verify the sign in form
    if form.validate_on_submit():

        user = User.query.filter_by(username=form.username_or_email.data).first()
        if not user:
            user = User.query.filter_by(email=form.username_or_email.data).first()

        if user and user.check_password(form.password.data):

            session['user_id'] = user.id
            
            #set permanent login, if selected
            if form.remember.data == True:
                session.permanent = True

            flash('Welcome %s' % user.name, 'success')
            
            return redirect(url_for('main_page_module.index'))

        flash('Wrong email or password', 'error')
    
    try:

app/templates/main_page_module/all_entry.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
{% endblock extraheader  %}

{% block nav_all_entry %}active{% endblock nav_all_entry %}


{% block flashes %}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <div>
        {% for category, message in messages %}
          {% if category == "error" %}
            <div class="alert alert-danger" role="alert">
              {{ message }}
            </div>
          {% else %}
            <div class="alert alert-success" role="alert">
              {{ message }}
            </div>
          {% endif %}
        {% endfor %}
      </div>
      <br>
    {% endif %}
  {% endwith %}
{% endblock flashes %}


{% block content%}

<legend>All Entries</legend>
<a href="{{ url_for('main_page_module.get_zipped_entries') }}" class="btn btn-warning btn-sm" role="button">Download the archive</a>

<div id="all_entries" class="container">
  {% for i in files%}
  <hr>
  <div class="media">
      <div class="btn-group btn-group-sm align-self-center mr-3" role="group" aria-label="...">
        <a href="{{ url_for('main_page_module.view_entry', entry_name=i[2]) }}" class="btn btn-secondary" role="button">View Entry</a>
        <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#{{ i[2] }}">Delete</button>
      </div>
    <div class="media-body">
      <h4 class="mt-0">{{ i[1] }}</h4>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="{{ i[2] }}" tabindex="-1" role="dialog" aria-labelledby="{{ i[2]+'text' }}" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="{{ i[2]+'text' }}">Delete the Entry</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Do you really want to delete the entry "{{ i[1] }}"
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          
          <form method="POST" action="{{ url_for('main_page_module.delete_entry') }}" accept-charset="UTF-8" role="form">
            <input type="hidden" id="id" name="id" value="{{ i[2] }}">
            <button type="submit" class="btn btn-danger">Delete entry</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  {% endfor %}
</div>

<hr>

{% endblock content %}

app/templates/main_page_module/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>

    </style>
    {% block extraheader %}
    {% endblock extraheader %}

    <title>Notes App</title>
  </head>
    
  <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ url_for('main_page_module.index') }}">MAIN MENU</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    
                    <li class="nav-item {% block nav_index %}{% endblock nav_index %}">
                        <a class="nav-link" href="{{ url_for('main_page_module.index') }}">Home </a>
                    </li>
                    <li class="nav-item {% block nav_new_entry %}{% endblock nav_new_entry %}">
                        <a class="nav-link" href="{{ url_for('main_page_module.new_entry') }}">New entry </a>
                    </li>
                    <li class="nav-item {% block nav_all_entry %}{% endblock nav_all_entry %}">
                        <a class="nav-link" href="{{ url_for('main_page_module.all_entry') }}">View All Entries </a>
                    </li>
                    <li class="nav-item {% block nav_all_users %}{% endblock nav_all_users %}">
                        <a class="nav-link" href="{{ url_for('main_page_module.all_users') }}">Users </a>
                    </li>
                    
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if session['user_id'] %}
                        <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main_page_module.logout') }}">Logout </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main_page_module.login') }}">Login </a>
                        </li>
                    {% endif %}
                </ul>
                
            </div>
        </nav>

    {% block flashes %}
    {% endblock %}
    
    <div class="container" style="background-color: rgb(255, 255, 255)">
        {% block content %}
        {% endblock %}
    </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/main_page_module/edit_entry.html
{% extends "main_page_module/base.html" %}


{% block extraheader %}
{% endblock %}

{% block nav_new_entry %}active{% endblock nav_new_entry %}


{% block flashes %}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <div>
        {% for category, message in messages %}
          {% if category == "error" %}
            <div class="alert alert-danger" role="alert">
              {{ message }}
            </div>
            <br>
          {% else %}
            <div class="alert alert-success" role="alert">
              {{ message }}
            </div>
            <br>
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}
  {% endwith %}
{% endblock %}


{% block content%}

{% macro render_field(field, placeholder=None) %}
<div class="form-group">
    {% set css_class = 'form-control ' + kwargs.pop('class', '') %}

    {{ field.label }}

    {% if field.errors %}
        {% set css_class = css_class + ' is-invalid' %}

        {% for error in field.errors %}
            
            <small id="{{ field.label.text }}" class="text-danger">
                {{ error }}
          </small>

        {% endfor %}
        </ul>
    {% endif %}

    {{ field(class=css_class, placeholder=placeholder, **kwargs) }}
</div>
{% endmacro %}


<div>
  <div>
    <legend>{{ entry_name }}</legend>

    <form method="POST" action="{{ url_for('main_page_module.edit_entry', entry_name=link_entry_name) }}" accept-charset="UTF-8" role="form">
      {{ form.csrf_token }}
      
      <div class="form-group">
          <textarea class="form-control " id="entry_text" name="entry_text" placeholder="Write what stuff" required rows="30">{{ entry_text }}</textarea>
      </div>
      <div class="form-group">
        {{ form.submit(class="form-control btn btn-primary mb-2", value="Submit eddits") }}
        </div>
    </form>
  </div>
</div>
{% endblock %}

app/templates/main_page_module/new_entry.html
{% extends "main_page_module/base.html" %}


{% block extraheader %}
{% endblock %}

{% block nav_new_entry %}active{% endblock nav_new_entry %}


{% block flashes %}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <div>
        {% for category, message in messages %}
          {% if category == "error" %}
            <div class="alert alert-danger" role="alert">
              {{ message }}
            </div>
            <br>
          {% else %}
            <div class="alert alert-success" role="alert">
              {{ message }}
            </div>
            <br>
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}
  {% endwith %}
{% endblock %}


{% block content%}

{% macro render_field(field, placeholder=None) %}
<div class="form-group">
    {% set css_class = 'form-control ' + kwargs.pop('class', '') %}

    {{ field.label }}

    {% if field.errors %}
        {% set css_class = css_class + ' is-invalid' %}

        {% for error in field.errors %}
            
            <small id="{{ field.label.text }}" class="text-danger">
                {{ error }}
          </small>

        {% endfor %}
        </ul>
    {% endif %}

    {{ field(class=css_class, placeholder=placeholder, **kwargs) }}
</div>
{% endmacro %}


<div>
  <div>
    <legend>New entry</legend>

    <form method="POST" action="{{ url_for('main_page_module.new_entry') }}" accept-charset="UTF-8" role="form">
      {{ form.csrf_token }}
      {{ render_field(form.name, placeholder="Enter the name of the new entry",
                                  autofocus="") }}
      {{ render_field(form.entry_text, placeholder="Write what stuff", rows='20') }}
      
      <div class="form-group">
        {{ form.submit(class="form-control btn btn-primary mb-2") }}
        </div>
    </form>
  </div>
</div>
{% endblock %}

app/templates/main_page_module/view_entry.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
{% endblock extraheader  %}

{% block nav_index %}active{% endblock nav_index %}


{% block flashes %}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <div>
        {% for category, message in messages %}
          {% if category == "error" %}
            <div class="alert alert-danger" role="alert">
              {{ message }}
            </div>
          {% else %}
            <div class="alert alert-success" role="alert">
              {{ message }}
            </div>
          {% endif %}
        {% endfor %}
      </div>
      <br>
    {% endif %}
  {% endwith %}
{% endblock flashes %}


{% block content%}

<legend>{{ entry_name }}</legend>


<hr>
{% filter markdown %}
{{ entry_text }}
{% endfilter %}

<div class="btn-group btn-group-sm" role="group" aria-label="...">
  <a href="{{ url_for('main_page_module.edit_entry', entry_name=link_entry_name) }}" class="btn btn-secondary" role="button">Edit Entry</a>
  <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#DeleteEntry">Delete</button>
</div>

<!-- Modal -->
<div class="modal fade" id="DeleteEntry" tabindex="-1" role="dialog" aria-labelledby="DeleteEntryTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="DeleteEntryTitle">Delete the Entry</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Do you really want to delete the entry "{{ entry_name }}"
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
        <form method="POST" action="{{ url_for('main_page_module.delete_entry') }}" accept-charset="UTF-8" role="form">
          <input type="hidden" id="id" name="id" value="{{ entry_name }}">
          <button type="submit" class="btn btn-danger">Delete entry</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}